### ISSUE TITLE
Organization

### ISSUE THREAD

**Issue by ai** [browserslist/browserslist-useragent#11]
@dmfrancisco suggested the great idea to create [`browserslist`](https://github.com/browserslist) organization and to move all repos to it.

I like the idea because it will increase the popularity of all browserslist-related tools. I will move `browserslist` and `browserslist-example`. @dmfrancisco will move `browserslist-ga`.

@pastelsky what do you think about moving your repo to the organization?

**Comment by dmfrancisco** [comment]
In my opinion this could be interesting because it may improve discoverability and gives the project a bigger sense of community (like those contrib accounts such as [webpack-contrib](https://github.com/webpack-contrib)). And I believe if someone starts contributing a lot, it can build a better sense of ownership than if the project was under a personal account.

Also in my case, in the occasion of getting hit by a bus, it would be nice if someone else in the Browserslist organization had the permissions to archive my repository or nominate a new maintainer.

But it's just my opinion and I understand if others feel differently 🙂

**Comment by pastelsky** [comment]
Let's do it 👍

**Comment by ai** [comment]
Awesome! I will move Browserslist at this Friday.
