### ISSUE TITLE
wrong result in matchesUA

### ISSUE THREAD

**Issue by budarin** [browserslist/browserslist-useragent#8]
I have userAgent string:
```
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36
```
and options:
```js
{
   browsers: ['Chrome >= 62'],
}
```
the result of :
```js
        matchesUA(ctx.userAgent.source, {
            browsers: ['Chrome >= 62'],
        })
```
is **false** but must be true

**Comment by GabrielDelepine** [comment]
@budarin I run my own tests and I think your issue was related to the version of `browserslist`

You are probably looking for the option `_allowHigherVersions`. More explanation in the following issue #10

**Comment by budarin** [comment]
it seems that the project is abandoned (

**Comment by pastelsky** [comment]
Sorry for taking so much time to reply. 
I had no clue that this project was seeing so much activity. This will be fixed in the next release - dependencies have been updated. 

However since chrome releases new versions very frequently, it's adviced to add `unreleased Chrome versions` to your browserslist, or set `_allowHigherVersions` to true as mentioned in the readme.

**Comment by pastelsky** [comment]
This has been fixed in the recent versions.
